version: '3.0'

services:
  calendar_cache:
    build: .
    image: calendar_cache
    ports:
      - '3000:3000'
    restart: always
    links:
      - redis
    volumes:
      - ./data:/app/data

  redis:
    image: redis
    container_name: calendar_cache_redis
    restart: always
    volumes:
      - ./data/cache:/data
