version: '3.0'

services:
  api:
    build: .
    ports:
      - '${PORT}:${PORT}'
    restart: always
    links:
      - 'cache:${REDIS_HOST:-redis}'
    volumes:
      - ./data:/app/data

  cache:
    image: redis
    restart: always
    volumes:
      - ./data/cache:/data
