version: '3.9'

services:
  api:
    build: .
    ports:
      - '${DOCKER_PORT:-8080}:${PORT:-8080}'
    restart: always
    links:
      - 'cache'
    volumes:
      - ./data:/app/data

  cache:
    image: redis:${REDIS_TAG:-latest}
    restart: always
    volumes:
      - ./data/cache:/data
